name: thesiswizard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  iconsax: ^0.0.8
  desktop_split_pane: ^1.0.3
  sidebarx: ^0.17.1
  # flutter_side_menu: ^0.5.3
  flutter_svg: ^2.0.10+1
  bitsdojo_window: ^0.1.6
  # flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          style: normal
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-ThinItalic.ttf
          weight: 400
          style: italic
    - family: IBM Plex Serif
      fonts:
        - asset: assets/fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          style: normal
        - asset: assets/fonts/IBM_Plex_Serif/IBMPlexSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBM_Plex_Serif/IBMPlexSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBM_Plex_Serif/IBMPlexSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/IBM_Plex_Serif/IBMPlexSerif-LightItalic.ttf
          weight: 400
          style: italic
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/Noto_Serif/NotoSerif-Italic-VariableFont_wdth,wght.ttf
          style: italic
        - asset: assets/fonts/Noto_Serif/NotoSerif-VariableFont_wdth,wght.ttf
          style: normal
    - family: Pt Serif
      fonts:
        - asset: assets/fonts/PT_Serif/PTSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/PT_Serif/PTSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/PT_Serif/PTSerif-Italic.ttf
          style: italic
        - asset: assets/fonts/PT_Serif/PTSerif-Regular.ttf
          style: normal
    - family: Roboto Serif
      fonts:
        - asset : assets/fonts/Roboto_Serif/RobotoSerif-Italic-VariableFont_GRAD,opsz,wdth,wght.ttf
          style: italic
        - asset : assets/fonts/Roboto_Serif/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf
          style: normal
    - family: newtx
      fonts:
        - asset: assets/fonts/newtx/TeXGyreTermesX-Bold.otf
          weight: 700
        - asset: assets/fonts/newtx/TeXGyreTermesX-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/newtx/TeXGyreTermesX-Italic.otf
          style: italic
        - asset: assets/fonts/newtx/TeXGyreTermesX-Regular.otf
          style: normal
    - family: newtxmath
      fonts:
        - asset: assets/fonts/tex-gyre-math/texgyreschola-math.otf
          style: normal
        - asset: assets/fonts/tex-gyre-math/texgyrebonum-math.otf
          style: normal
          weight: 500


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
